language: node_js
node_js:
  - "10"

git:
  depth: 1

script:
  - (cd nodejs; npm install)

before_deploy:
  - cd nodejs

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  on:
    repo: IBM-Blockchain-Identity/openssi-websdk
    tags: true